export const MUNICIPIOS =
[
    {id:37, name:"Paratebueno"},
{id:36, name:"Medina"},
{id:33, name:"Guayabetal"},
{id:29, name:"Quetame"},
{id:31, name:"Caqueza"},
{id:26, name:"Ubaque"},
{id:4	, name:"Simijaca"},
{id:35, name:"Susa"},
{id:3	, name:"Tausa"},
{id:1	, name:"Cajica"},
{id:2	, name:"Gachancipa"},
{id:41, name:"Venecia"},
{id:40, name:"Tibacuy"},
{id:42, name:"Granada"},
{id:43, name:"Sibate"},
{id:39, name:"Arbelaez"},
{id:14, name:"Villeta"},
{id:16, name:"La Vega"},
{id:18, name:"Alban"},
{id:17, name:"Sasaima"},
{id:21, name:"Cachipay"},
{id:12, name:"Quebradanegra"},
{id:22, name:"Anapoima"},
{id:23, name:"Apulo"},
{id:24, name:"Tocaima"},
{id:44, name:"Ricaurte"},
{id:45, name:"Agua de Dios"},
{id:28, name:"Une"},
{id:38, name:"Nilo"},
{id:5	, name:"Yacopi"},
{id:7	, name:"Caparrapi"},
{id:8	, name:"La Palma"},
{id:10, name:"La Peña"},
{id:19, name:"Beltran"},
{id:20, name:"Puli"},
{id:15, name:"Supata"},
{id:13, name:"Vergara"},
{id:11, name:"Nimaima"},
{id:9	, name:"Villa Gomez"},
{id:6	, name:"Paime"},
{id:25, name:"Choachi"},
{id:30, name:"Chipaque"},
{id:32, name:"Fosca"},
{id:34, name:"Gutierrez"},
{id:27, name:"Fomeque"}

]